/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaszamologepmenyharttamas;

import static java.lang.Math.pow;
import static java.lang.Math.sqrt;
import java.util.ArrayList;

/**
 *
 * @author Kecyke
 */
public class foablak extends javax.swing.JFrame {

    /**
     * Creates new form foablak
     */
    public foablak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fopanel = new javax.swing.JPanel();
        outputslot = new java.awt.TextField();
        bemenetlabel = new javax.swing.JLabel();
        inputslot = new java.awt.TextField();
        kimenetlabel = new javax.swing.JLabel();
        userinterface = new javax.swing.JPanel();
        szamok = new javax.swing.JPanel();
        begyes = new javax.swing.JButton();
        bkettes = new javax.swing.JButton();
        bharmas = new javax.swing.JButton();
        bnegyes = new javax.swing.JButton();
        botos = new javax.swing.JButton();
        bhatos = new javax.swing.JButton();
        bhetes = new javax.swing.JButton();
        bnyolcas = new javax.swing.JButton();
        bkilences = new javax.swing.JButton();
        bnullas = new javax.swing.JButton();
        be = new javax.swing.JButton();
        bpi = new javax.swing.JButton();
        muveletjelpanel = new javax.swing.JPanel();
        bosszeadas = new javax.swing.JButton();
        bkivonas = new javax.swing.JButton();
        bszorzas = new javax.swing.JButton();
        bosztas = new javax.swing.JButton();
        bhatvanyozas = new javax.swing.JButton();
        bgyokvonas = new javax.swing.JButton();
        bnyitozarojel = new javax.swing.JButton();
        bbezarozarojel = new javax.swing.JButton();
        bnchoosek = new javax.swing.JButton();
        btorles = new javax.swing.JButton();
        begyenlosegjel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        muveletijelek = new javax.swing.JMenu();
        osszeadas = new javax.swing.JCheckBoxMenuItem();
        kivonas = new javax.swing.JCheckBoxMenuItem();
        szorzas = new javax.swing.JCheckBoxMenuItem();
        osztas = new javax.swing.JCheckBoxMenuItem();
        hatvanyozas = new javax.swing.JCheckBoxMenuItem();
        gyokvonas = new javax.swing.JCheckBoxMenuItem();
        nyitozarojel = new javax.swing.JCheckBoxMenuItem();
        bezarozarojel = new javax.swing.JCheckBoxMenuItem();
        torles = new javax.swing.JCheckBoxMenuItem();
        egyenlosegjel = new javax.swing.JCheckBoxMenuItem();
        fejleszto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputslot.setBackground(new java.awt.Color(102, 255, 255));
        outputslot.setEditable(false);
        outputslot.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        outputslot.setText("");
        outputslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputslotActionPerformed(evt);
            }
        });

        bemenetlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bemenetlabel.setText("Bemenet:");

        inputslot.setBackground(new java.awt.Color(102, 255, 102));
        inputslot.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputslot.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputslot.setText("");
        inputslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputslotActionPerformed(evt);
            }
        });

        kimenetlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kimenetlabel.setText("Kimenet:");

        szamok.setMaximumSize(new java.awt.Dimension(150, 200));
        szamok.setMinimumSize(new java.awt.Dimension(150, 200));

        begyes.setBackground(new java.awt.Color(0, 255, 51));
        begyes.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        begyes.setText("1");
        begyes.setMaximumSize(new java.awt.Dimension(50, 50));
        begyes.setMinimumSize(new java.awt.Dimension(50, 50));
        begyes.setPreferredSize(new java.awt.Dimension(50, 50));
        begyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                begyesActionPerformed(evt);
            }
        });
        szamok.add(begyes);

        bkettes.setBackground(new java.awt.Color(0, 255, 51));
        bkettes.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bkettes.setText("2");
        bkettes.setMaximumSize(new java.awt.Dimension(50, 50));
        bkettes.setMinimumSize(new java.awt.Dimension(50, 50));
        bkettes.setPreferredSize(new java.awt.Dimension(50, 50));
        bkettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkettesActionPerformed(evt);
            }
        });
        szamok.add(bkettes);

        bharmas.setBackground(new java.awt.Color(0, 255, 51));
        bharmas.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bharmas.setText("3");
        bharmas.setMaximumSize(new java.awt.Dimension(50, 50));
        bharmas.setMinimumSize(new java.awt.Dimension(50, 50));
        bharmas.setPreferredSize(new java.awt.Dimension(50, 50));
        bharmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bharmasActionPerformed(evt);
            }
        });
        szamok.add(bharmas);

        bnegyes.setBackground(new java.awt.Color(0, 255, 51));
        bnegyes.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bnegyes.setText("4");
        bnegyes.setMaximumSize(new java.awt.Dimension(50, 50));
        bnegyes.setMinimumSize(new java.awt.Dimension(50, 50));
        bnegyes.setPreferredSize(new java.awt.Dimension(50, 50));
        bnegyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnegyesActionPerformed(evt);
            }
        });
        szamok.add(bnegyes);

        botos.setBackground(new java.awt.Color(0, 255, 51));
        botos.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        botos.setText("5");
        botos.setMaximumSize(new java.awt.Dimension(50, 50));
        botos.setMinimumSize(new java.awt.Dimension(50, 50));
        botos.setPreferredSize(new java.awt.Dimension(50, 50));
        botos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botosActionPerformed(evt);
            }
        });
        szamok.add(botos);

        bhatos.setBackground(new java.awt.Color(0, 255, 51));
        bhatos.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bhatos.setText("6");
        bhatos.setMaximumSize(new java.awt.Dimension(50, 50));
        bhatos.setMinimumSize(new java.awt.Dimension(50, 50));
        bhatos.setPreferredSize(new java.awt.Dimension(50, 50));
        bhatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhatosActionPerformed(evt);
            }
        });
        szamok.add(bhatos);

        bhetes.setBackground(new java.awt.Color(0, 255, 51));
        bhetes.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bhetes.setText("7");
        bhetes.setMaximumSize(new java.awt.Dimension(50, 50));
        bhetes.setMinimumSize(new java.awt.Dimension(50, 50));
        bhetes.setPreferredSize(new java.awt.Dimension(50, 50));
        bhetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhetesActionPerformed(evt);
            }
        });
        szamok.add(bhetes);

        bnyolcas.setBackground(new java.awt.Color(0, 255, 51));
        bnyolcas.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bnyolcas.setText("8");
        bnyolcas.setMaximumSize(new java.awt.Dimension(50, 50));
        bnyolcas.setMinimumSize(new java.awt.Dimension(50, 50));
        bnyolcas.setPreferredSize(new java.awt.Dimension(50, 50));
        bnyolcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnyolcasActionPerformed(evt);
            }
        });
        szamok.add(bnyolcas);

        bkilences.setBackground(new java.awt.Color(0, 255, 51));
        bkilences.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bkilences.setText("9");
        bkilences.setMaximumSize(new java.awt.Dimension(50, 50));
        bkilences.setMinimumSize(new java.awt.Dimension(50, 50));
        bkilences.setPreferredSize(new java.awt.Dimension(50, 50));
        bkilences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkilencesActionPerformed(evt);
            }
        });
        szamok.add(bkilences);

        bnullas.setBackground(new java.awt.Color(0, 255, 51));
        bnullas.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bnullas.setText("0");
        bnullas.setMaximumSize(new java.awt.Dimension(50, 50));
        bnullas.setMinimumSize(new java.awt.Dimension(50, 50));
        bnullas.setPreferredSize(new java.awt.Dimension(50, 50));
        bnullas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnullasActionPerformed(evt);
            }
        });
        szamok.add(bnullas);

        be.setBackground(new java.awt.Color(0, 255, 51));
        be.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        be.setText("e");
        be.setMaximumSize(new java.awt.Dimension(50, 50));
        be.setMinimumSize(new java.awt.Dimension(50, 50));
        be.setPreferredSize(new java.awt.Dimension(50, 50));
        be.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beActionPerformed(evt);
            }
        });
        szamok.add(be);

        bpi.setBackground(new java.awt.Color(0, 255, 51));
        bpi.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bpi.setText("π");
        bpi.setMaximumSize(new java.awt.Dimension(50, 50));
        bpi.setMinimumSize(new java.awt.Dimension(50, 50));
        bpi.setPreferredSize(new java.awt.Dimension(50, 50));
        bpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpiActionPerformed(evt);
            }
        });
        szamok.add(bpi);

        bosszeadas.setBackground(new java.awt.Color(255, 255, 255));
        bosszeadas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosszeadas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/IXgglOn.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosszeadas.setToolTipText("");
        bosszeadas.setBorder(null);
        bosszeadas.setMinimumSize(new java.awt.Dimension(0, 0));
        bosszeadas.setName(""); // NOI18N
        bosszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosszeadasActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bosszeadas);

        bkivonas.setBackground(new java.awt.Color(255, 255, 255));
        bkivonas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bkivonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/E1zvKG7.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bkivonas.setBorder(null);
        bkivonas.setMinimumSize(new java.awt.Dimension(0, 0));
        bkivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkivonasActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bkivonas);

        bszorzas.setBackground(new java.awt.Color(255, 255, 255));
        bszorzas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bszorzas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BJ4yusU.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bszorzas.setToolTipText("");
        bszorzas.setBorder(null);
        bszorzas.setMinimumSize(new java.awt.Dimension(0, 0));
        bszorzas.setName(""); // NOI18N
        bszorzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bszorzasActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bszorzas);

        bosztas.setBackground(new java.awt.Color(255, 255, 255));
        bosztas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosztas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/wxRhK3i.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosztas.setToolTipText("");
        bosztas.setBorder(null);
        bosztas.setMinimumSize(new java.awt.Dimension(0, 0));
        bosztas.setName(""); // NOI18N
        bosztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosztasActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bosztas);

        bhatvanyozas.setBackground(new java.awt.Color(255, 255, 255));
        bhatvanyozas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bhatvanyozas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BPVKHpZ.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bhatvanyozas.setToolTipText("");
        bhatvanyozas.setBorder(null);
        bhatvanyozas.setMinimumSize(new java.awt.Dimension(0, 0));
        bhatvanyozas.setName(""); // NOI18N
        bhatvanyozas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhatvanyozasActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bhatvanyozas);

        bgyokvonas.setBackground(new java.awt.Color(255, 255, 255));
        bgyokvonas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bgyokvonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/YPyBcOe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bgyokvonas.setToolTipText("");
        bgyokvonas.setBorder(null);
        bgyokvonas.setMinimumSize(new java.awt.Dimension(0, 0));
        bgyokvonas.setName(""); // NOI18N
        bgyokvonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgyokvonasActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bgyokvonas);

        bnyitozarojel.setBackground(new java.awt.Color(255, 255, 255));
        bnyitozarojel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bnyitozarojel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/4xnGmGs.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bnyitozarojel.setToolTipText("");
        bnyitozarojel.setBorder(null);
        bnyitozarojel.setMinimumSize(new java.awt.Dimension(0, 0));
        bnyitozarojel.setName(""); // NOI18N
        bnyitozarojel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnyitozarojelActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bnyitozarojel);

        bbezarozarojel.setBackground(new java.awt.Color(255, 255, 255));
        bbezarozarojel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bbezarozarojel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/w5eLMzB.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bbezarozarojel.setToolTipText("");
        bbezarozarojel.setBorder(null);
        bbezarozarojel.setMinimumSize(new java.awt.Dimension(0, 0));
        bbezarozarojel.setName(""); // NOI18N
        bbezarozarojel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbezarozarojelActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bbezarozarojel);

        bnchoosek.setBackground(new java.awt.Color(255, 255, 255));
        bnchoosek.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bnchoosek.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/Mkog7YC.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bnchoosek.setToolTipText("");
        bnchoosek.setBorder(null);
        bnchoosek.setMinimumSize(new java.awt.Dimension(0, 0));
        bnchoosek.setName(""); // NOI18N
        bnchoosek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnchoosekActionPerformed(evt);
            }
        });
        muveletjelpanel.add(bnchoosek);

        btorles.setBackground(new java.awt.Color(255, 255, 255));
        btorles.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btorles.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/5BUQAEv.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btorles.setToolTipText("");
        btorles.setBorder(null);
        btorles.setMinimumSize(new java.awt.Dimension(0, 0));
        btorles.setName(""); // NOI18N
        btorles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btorlesActionPerformed(evt);
            }
        });
        muveletjelpanel.add(btorles);

        begyenlosegjel.setBackground(new java.awt.Color(255, 255, 255));
        begyenlosegjel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        begyenlosegjel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/3fxHcBe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        begyenlosegjel.setToolTipText("");
        begyenlosegjel.setBorder(null);
        begyenlosegjel.setMinimumSize(new java.awt.Dimension(0, 0));
        begyenlosegjel.setName(""); // NOI18N
        begyenlosegjel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                begyenlosegjelActionPerformed(evt);
            }
        });
        muveletjelpanel.add(begyenlosegjel);

        javax.swing.GroupLayout userinterfaceLayout = new javax.swing.GroupLayout(userinterface);
        userinterface.setLayout(userinterfaceLayout);
        userinterfaceLayout.setHorizontalGroup(
            userinterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(szamok, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muveletjelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userinterfaceLayout.setVerticalGroup(
            userinterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userinterfaceLayout.createSequentialGroup()
                .addGroup(userinterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(szamok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muveletjelpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout fopanelLayout = new javax.swing.GroupLayout(fopanel);
        fopanel.setLayout(fopanelLayout);
        fopanelLayout.setHorizontalGroup(
            fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userinterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fopanelLayout.createSequentialGroup()
                        .addGroup(fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bemenetlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kimenetlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fopanelLayout.createSequentialGroup()
                        .addGroup(fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputslot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputslot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        fopanelLayout.setVerticalGroup(
            fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemenetlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kimenetlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userinterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        muveletijelek.setText("Műveleti Jelek");
        muveletijelek.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                muveletijelekStateChanged(evt);
            }
        });

        osszeadas.setSelected(true);
        osszeadas.setText("Összeadás");
        osszeadas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/IXgglOn.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        osszeadas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                osszeadasStateChanged(evt);
            }
        });
        osszeadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osszeadasMouseClicked(evt);
            }
        });
        osszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osszeadasActionPerformed(evt);
            }
        });
        muveletijelek.add(osszeadas);

        kivonas.setSelected(true);
        kivonas.setText("Kivonás");
        kivonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/E1zvKG7.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        kivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kivonasActionPerformed(evt);
            }
        });
        muveletijelek.add(kivonas);

        szorzas.setSelected(true);
        szorzas.setText("Szorzás");
        szorzas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BJ4yusU.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(szorzas);

        osztas.setSelected(true);
        osztas.setText("Osztás");
        osztas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/wxRhK3i.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(osztas);

        hatvanyozas.setSelected(true);
        hatvanyozas.setText("Hatványozás (pow(a,b))");
        hatvanyozas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BPVKHpZ.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        hatvanyozas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatvanyozasActionPerformed(evt);
            }
        });
        muveletijelek.add(hatvanyozas);

        gyokvonas.setSelected(true);
        gyokvonas.setText("Gyökvonás (sqrt(a,b))");
        gyokvonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/YPyBcOe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        gyokvonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gyokvonasActionPerformed(evt);
            }
        });
        muveletijelek.add(gyokvonas);

        nyitozarojel.setSelected(true);
        nyitozarojel.setText("Nyitó Zárójel");
        nyitozarojel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/4xnGmGs.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        nyitozarojel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nyitozarojelStateChanged(evt);
            }
        });
        nyitozarojel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nyitozarojelMouseClicked(evt);
            }
        });
        nyitozarojel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyitozarojelActionPerformed(evt);
            }
        });
        muveletijelek.add(nyitozarojel);

        bezarozarojel.setSelected(true);
        bezarozarojel.setText("Záró Zárójel");
        bezarozarojel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/w5eLMzB.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bezarozarojel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bezarozarojelStateChanged(evt);
            }
        });
        bezarozarojel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bezarozarojelMouseClicked(evt);
            }
        });
        bezarozarojel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bezarozarojelActionPerformed(evt);
            }
        });
        muveletijelek.add(bezarozarojel);

        torles.setSelected(true);
        torles.setText("Törlés");
        torles.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/5BUQAEv.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        torles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torlesActionPerformed(evt);
            }
        });
        muveletijelek.add(torles);

        egyenlosegjel.setSelected(true);
        egyenlosegjel.setText("Egyenlőségjel");
        egyenlosegjel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/3fxHcBe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        egyenlosegjel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egyenlosegjelActionPerformed(evt);
            }
        });
        muveletijelek.add(egyenlosegjel);

        jMenuBar1.add(muveletijelek);

        fejleszto.setText("Fejlesztő: Menyhárt Tamás (DE-IK)");
        jMenuBar1.add(fejleszto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //------------------------------------------------------------------------//
    //inputslot's input
    private ArrayList<String>input=new ArrayList<>();
    
    //hibakimenet
    String cerr="Valami hiba történt";
    
    //value of symbols
    private double pi=3.1415926535;
    private double e=2.7182818284;
    
    
    
    // Token ///////////////////////
    private class Token 
    {
	public String tipus;
	public double ertek;
	public String nev;
	public Token()
        {
            tipus=null;
        }
        public Token(String ch)
        {
            tipus=ch;
            ertek=0;
        }
        public Token(String ch, double val)
        {
            tipus=ch;
            ertek=val;
        }
        public Token(String ch, String n)                                                       
        {
            tipus=ch;
            nev=n;
        }
    }
    // Token end ///////////////////////

    
    private void osszeadasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_osszeadasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasStateChanged

    private void osszeadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osszeadasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasMouseClicked

    private void osszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osszeadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasActionPerformed

    private void kivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kivonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kivonasActionPerformed

    private void hatvanyozasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatvanyozasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hatvanyozasActionPerformed

    private void gyokvonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gyokvonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gyokvonasActionPerformed

    private void nyitozarojelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nyitozarojelStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nyitozarojelStateChanged

    private void nyitozarojelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nyitozarojelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nyitozarojelMouseClicked

    private void nyitozarojelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyitozarojelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyitozarojelActionPerformed

    private void bezarozarojelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bezarozarojelStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bezarozarojelStateChanged

    private void bezarozarojelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bezarozarojelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bezarozarojelMouseClicked

    private void bezarozarojelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bezarozarojelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bezarozarojelActionPerformed

    private void torlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_torlesActionPerformed

    private void egyenlosegjelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egyenlosegjelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egyenlosegjelActionPerformed

    private void muveletijelekStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_muveletijelekStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_muveletijelekStateChanged

    private void outputslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputslotActionPerformed

    private void inputslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputslotActionPerformed

    private void begyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_begyesActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"1");
    }//GEN-LAST:event_begyesActionPerformed

    private void bkettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkettesActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"2");
    }//GEN-LAST:event_bkettesActionPerformed

    private void bharmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bharmasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"3");
    }//GEN-LAST:event_bharmasActionPerformed

    private void bnegyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnegyesActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"4");
    }//GEN-LAST:event_bnegyesActionPerformed

    private void botosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botosActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"5");
    }//GEN-LAST:event_botosActionPerformed

    private void bhatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhatosActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"6");
    }//GEN-LAST:event_bhatosActionPerformed

    private void bhetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhetesActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"7");
    }//GEN-LAST:event_bhetesActionPerformed

    private void bnyolcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnyolcasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"8");
    }//GEN-LAST:event_bnyolcasActionPerformed

    private void bkilencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkilencesActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"9");
    }//GEN-LAST:event_bkilencesActionPerformed

    private void bnullasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnullasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"0");
    }//GEN-LAST:event_bnullasActionPerformed

    private void bosszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosszeadasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"+");
    }//GEN-LAST:event_bosszeadasActionPerformed

    private void bkivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkivonasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"-");
    }//GEN-LAST:event_bkivonasActionPerformed

    private void bszorzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bszorzasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"*");
    }//GEN-LAST:event_bszorzasActionPerformed

    private void bosztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosztasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"/");
    }//GEN-LAST:event_bosztasActionPerformed

    private void bhatvanyozasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhatvanyozasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"pow(");
    }//GEN-LAST:event_bhatvanyozasActionPerformed

    private void bgyokvonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgyokvonasActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"sqrt(");
    }//GEN-LAST:event_bgyokvonasActionPerformed

    private void bnyitozarojelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnyitozarojelActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"(");
    }//GEN-LAST:event_bnyitozarojelActionPerformed

    private void bbezarozarojelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbezarozarojelActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+")");
    }//GEN-LAST:event_bbezarozarojelActionPerformed

    private void btorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btorlesActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText().substring(0,inputslot.getText().length()-1));
    }//GEN-LAST:event_btorlesActionPerformed

    private void begyenlosegjelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_begyenlosegjelActionPerformed
        // TODO add your handling code here:
        if(inputslot.getText().substring(inputslot.getText().length()-1).equals("=")==false)
        {
            inputslot.setText(inputslot.getText() + "=");
        }
        String text=inputslot.getText();
        for (int i=0; i<text.length(); i++)
        {
            input.add(text.charAt(i)+"");
        }
        //main();
        while(!input.isEmpty())
        {
            input.remove(0);
        }
    }//GEN-LAST:event_begyenlosegjelActionPerformed

    private void bnchoosekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnchoosekActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"nchoosek(");
    }//GEN-LAST:event_bnchoosekActionPerformed

    private void beActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"e");
    }//GEN-LAST:event_beActionPerformed

    private void bpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpiActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"π");
    }//GEN-LAST:event_bpiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbezarozarojel;
    private javax.swing.JButton be;
    private javax.swing.JButton begyenlosegjel;
    private javax.swing.JButton begyes;
    private javax.swing.JLabel bemenetlabel;
    private javax.swing.JCheckBoxMenuItem bezarozarojel;
    private javax.swing.JButton bgyokvonas;
    private javax.swing.JButton bharmas;
    private javax.swing.JButton bhatos;
    private javax.swing.JButton bhatvanyozas;
    private javax.swing.JButton bhetes;
    private javax.swing.JButton bkettes;
    private javax.swing.JButton bkilences;
    private javax.swing.JButton bkivonas;
    private javax.swing.JButton bnchoosek;
    private javax.swing.JButton bnegyes;
    private javax.swing.JButton bnullas;
    private javax.swing.JButton bnyitozarojel;
    private javax.swing.JButton bnyolcas;
    private javax.swing.JButton bosszeadas;
    private javax.swing.JButton bosztas;
    private javax.swing.JButton botos;
    private javax.swing.JButton bpi;
    private javax.swing.JButton bszorzas;
    private javax.swing.JButton btorles;
    private javax.swing.JCheckBoxMenuItem egyenlosegjel;
    private javax.swing.JMenu fejleszto;
    private javax.swing.JPanel fopanel;
    private javax.swing.JCheckBoxMenuItem gyokvonas;
    private javax.swing.JCheckBoxMenuItem hatvanyozas;
    private java.awt.TextField inputslot;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel kimenetlabel;
    private javax.swing.JCheckBoxMenuItem kivonas;
    private javax.swing.JMenu muveletijelek;
    private javax.swing.JPanel muveletjelpanel;
    private javax.swing.JCheckBoxMenuItem nyitozarojel;
    private javax.swing.JCheckBoxMenuItem osszeadas;
    private javax.swing.JCheckBoxMenuItem osztas;
    private java.awt.TextField outputslot;
    private javax.swing.JPanel szamok;
    private javax.swing.JCheckBoxMenuItem szorzas;
    private javax.swing.JCheckBoxMenuItem torles;
    private javax.swing.JPanel userinterface;
    // End of variables declaration//GEN-END:variables
}
