/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menyharttamasszamologep;

/**
 *
 * @author EgyipTomi425
 */
public class foablak extends javax.swing.JFrame {

    /**
     * Creates new form foablak
     */
    public foablak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fopanel = new javax.swing.JPanel();
        inputslot = new java.awt.TextField();
        bemenetlabel = new javax.swing.JLabel();
        outputslot = new java.awt.TextField();
        kimenetlabel = new javax.swing.JLabel();
        userinterface = new javax.swing.JPanel();
        szamok = new javax.swing.JPanel();
        egyes = new javax.swing.JButton();
        muveletjelpanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        muveletijelek = new javax.swing.JMenu();
        osszeadas = new javax.swing.JCheckBoxMenuItem();
        kivonas = new javax.swing.JCheckBoxMenuItem();
        szorzas = new javax.swing.JCheckBoxMenuItem();
        osztas = new javax.swing.JCheckBoxMenuItem();
        hatvanyozas = new javax.swing.JCheckBoxMenuItem();
        gyokvonas = new javax.swing.JCheckBoxMenuItem();
        csakegymenu = new javax.swing.JMenu();
        fejleszto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputslot.setBackground(new java.awt.Color(102, 255, 255));
        inputslot.setEditable(false);
        inputslot.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputslot.setText("");
        inputslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputslotActionPerformed(evt);
            }
        });

        bemenetlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bemenetlabel.setText("Bemenet:");

        outputslot.setBackground(new java.awt.Color(102, 255, 102));
        outputslot.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        outputslot.setText("");
        outputslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputslotActionPerformed(evt);
            }
        });

        kimenetlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kimenetlabel.setText("Kimenet:");

        userinterface.setLayout(new java.awt.BorderLayout());

        szamok.setLayout(new javax.swing.BoxLayout(szamok, javax.swing.BoxLayout.LINE_AXIS));

        egyes.setBackground(new java.awt.Color(0, 255, 51));
        egyes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        egyes.setText("1");
        szamok.add(egyes);

        userinterface.add(szamok, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout muveletjelpanelLayout = new javax.swing.GroupLayout(muveletjelpanel);
        muveletjelpanel.setLayout(muveletjelpanelLayout);
        muveletjelpanelLayout.setHorizontalGroup(
            muveletjelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        muveletjelpanelLayout.setVerticalGroup(
            muveletjelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        userinterface.add(muveletjelpanel, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout fopanelLayout = new javax.swing.GroupLayout(fopanel);
        fopanel.setLayout(fopanelLayout);
        fopanelLayout.setHorizontalGroup(
            fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userinterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputslot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputslot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fopanelLayout.createSequentialGroup()
                        .addGroup(fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bemenetlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kimenetlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fopanelLayout.setVerticalGroup(
            fopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemenetlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kimenetlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userinterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        muveletijelek.setText("Műveleti Jelek");

        osszeadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        osszeadas.setSelected(true);
        osszeadas.setText("Összeadás");
        osszeadas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/IXgglOn.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        osszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osszeadasActionPerformed(evt);
            }
        });
        muveletijelek.add(osszeadas);

        kivonas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, 0));
        kivonas.setSelected(true);
        kivonas.setText("Kivonás");
        kivonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/E1zvKG7.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(kivonas);

        szorzas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        szorzas.setSelected(true);
        szorzas.setText("Szorzás");
        szorzas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BJ4yusU.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(szorzas);

        osztas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        osztas.setSelected(true);
        osztas.setText("Osztás");
        osztas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/wxRhK3i.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(osztas);

        hatvanyozas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        hatvanyozas.setSelected(true);
        hatvanyozas.setText("Hatványozás");
        hatvanyozas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BPVKHpZ.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(hatvanyozas);

        gyokvonas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        gyokvonas.setSelected(true);
        gyokvonas.setText("Gyökvonás");
        gyokvonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/YPyBcOe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(gyokvonas);

        jMenuBar1.add(muveletijelek);

        csakegymenu.setText("_________________________________________________________");
        jMenuBar1.add(csakegymenu);

        fejleszto.setText("Fejlesztő: Menyhárt Tamás (DE-IK)");
        jMenuBar1.add(fejleszto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void osszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osszeadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasActionPerformed

    private void inputslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputslotActionPerformed

    private void outputslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputslotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemenetlabel;
    private javax.swing.JMenu csakegymenu;
    private javax.swing.JButton egyes;
    private javax.swing.JMenu fejleszto;
    private javax.swing.JPanel fopanel;
    private javax.swing.JCheckBoxMenuItem gyokvonas;
    private javax.swing.JCheckBoxMenuItem hatvanyozas;
    private java.awt.TextField inputslot;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel kimenetlabel;
    private javax.swing.JCheckBoxMenuItem kivonas;
    private javax.swing.JMenu muveletijelek;
    private javax.swing.JPanel muveletjelpanel;
    private javax.swing.JCheckBoxMenuItem osszeadas;
    private javax.swing.JCheckBoxMenuItem osztas;
    private java.awt.TextField outputslot;
    private javax.swing.JPanel szamok;
    private javax.swing.JCheckBoxMenuItem szorzas;
    private javax.swing.JPanel userinterface;
    // End of variables declaration//GEN-END:variables
}
