/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.menyharttamasszamologep;

/**
 *
 * @author Kecyke
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fopanel8 = new javax.swing.JPanel();
        outputslot8 = new java.awt.TextField();
        bemenetlabel8 = new javax.swing.JLabel();
        inputslot8 = new java.awt.TextField();
        kimenetlabel8 = new javax.swing.JLabel();
        userinterface8 = new javax.swing.JPanel();
        szamok8 = new javax.swing.JPanel();
        egyes8 = new javax.swing.JButton();
        kettes8 = new javax.swing.JButton();
        harmas8 = new javax.swing.JButton();
        negyes8 = new javax.swing.JButton();
        otos8 = new javax.swing.JButton();
        hatos8 = new javax.swing.JButton();
        hetes8 = new javax.swing.JButton();
        nyolcas8 = new javax.swing.JButton();
        kilences8 = new javax.swing.JButton();
        nullas8 = new javax.swing.JButton();
        xgomb8 = new javax.swing.JButton();
        ygomb8 = new javax.swing.JButton();
        muveletjelpanel8 = new javax.swing.JPanel();
        bosszeadas40 = new javax.swing.JButton();
        bkivonas8 = new javax.swing.JButton();
        bosszeadas41 = new javax.swing.JButton();
        bosszeadas42 = new javax.swing.JButton();
        bosszeadas43 = new javax.swing.JButton();
        bosszeadas44 = new javax.swing.JButton();
        bnyitozarojel8 = new javax.swing.JButton();
        bbezarozarojel8 = new javax.swing.JButton();
        btorles8 = new javax.swing.JButton();
        begyenlosegjel8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        muveletijelek = new javax.swing.JMenu();
        osszeadas = new javax.swing.JCheckBoxMenuItem();
        kivonas = new javax.swing.JCheckBoxMenuItem();
        szorzas = new javax.swing.JCheckBoxMenuItem();
        osztas = new javax.swing.JCheckBoxMenuItem();
        hatvanyozas = new javax.swing.JCheckBoxMenuItem();
        gyokvonas = new javax.swing.JCheckBoxMenuItem();
        nyitozarojel = new javax.swing.JCheckBoxMenuItem();
        bezarozarojel = new javax.swing.JCheckBoxMenuItem();
        torles = new javax.swing.JCheckBoxMenuItem();
        egyenlosegjel = new javax.swing.JCheckBoxMenuItem();
        fejleszto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputslot8.setBackground(new java.awt.Color(102, 255, 255));
        outputslot8.setEditable(false);
        outputslot8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        outputslot8.setText("");
        outputslot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputslot8ActionPerformed(evt);
            }
        });

        bemenetlabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bemenetlabel8.setText("Bemenet:");

        inputslot8.setBackground(new java.awt.Color(102, 255, 102));
        inputslot8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputslot8.setText("");
        inputslot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputslot8ActionPerformed(evt);
            }
        });

        kimenetlabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kimenetlabel8.setText("Kimenet:");

        szamok8.setMaximumSize(new java.awt.Dimension(150, 200));
        szamok8.setMinimumSize(new java.awt.Dimension(150, 200));

        egyes8.setBackground(new java.awt.Color(0, 255, 51));
        egyes8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        egyes8.setText("1");
        egyes8.setMaximumSize(new java.awt.Dimension(50, 50));
        egyes8.setMinimumSize(new java.awt.Dimension(50, 50));
        egyes8.setPreferredSize(new java.awt.Dimension(50, 50));
        egyes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egyes8ActionPerformed(evt);
            }
        });
        szamok8.add(egyes8);

        kettes8.setBackground(new java.awt.Color(0, 255, 51));
        kettes8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        kettes8.setText("2");
        kettes8.setMaximumSize(new java.awt.Dimension(50, 50));
        kettes8.setMinimumSize(new java.awt.Dimension(50, 50));
        kettes8.setPreferredSize(new java.awt.Dimension(50, 50));
        kettes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kettes8ActionPerformed(evt);
            }
        });
        szamok8.add(kettes8);

        harmas8.setBackground(new java.awt.Color(0, 255, 51));
        harmas8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        harmas8.setText("3");
        harmas8.setMaximumSize(new java.awt.Dimension(50, 50));
        harmas8.setMinimumSize(new java.awt.Dimension(50, 50));
        harmas8.setPreferredSize(new java.awt.Dimension(50, 50));
        harmas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harmas8ActionPerformed(evt);
            }
        });
        szamok8.add(harmas8);

        negyes8.setBackground(new java.awt.Color(0, 255, 51));
        negyes8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        negyes8.setText("4");
        negyes8.setMaximumSize(new java.awt.Dimension(50, 50));
        negyes8.setMinimumSize(new java.awt.Dimension(50, 50));
        negyes8.setPreferredSize(new java.awt.Dimension(50, 50));
        negyes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negyes8ActionPerformed(evt);
            }
        });
        szamok8.add(negyes8);

        otos8.setBackground(new java.awt.Color(0, 255, 51));
        otos8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        otos8.setText("5");
        otos8.setMaximumSize(new java.awt.Dimension(50, 50));
        otos8.setMinimumSize(new java.awt.Dimension(50, 50));
        otos8.setPreferredSize(new java.awt.Dimension(50, 50));
        otos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otos8ActionPerformed(evt);
            }
        });
        szamok8.add(otos8);

        hatos8.setBackground(new java.awt.Color(0, 255, 51));
        hatos8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        hatos8.setText("6");
        hatos8.setMaximumSize(new java.awt.Dimension(50, 50));
        hatos8.setMinimumSize(new java.awt.Dimension(50, 50));
        hatos8.setPreferredSize(new java.awt.Dimension(50, 50));
        hatos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatos8ActionPerformed(evt);
            }
        });
        szamok8.add(hatos8);

        hetes8.setBackground(new java.awt.Color(0, 255, 51));
        hetes8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        hetes8.setText("7");
        hetes8.setMaximumSize(new java.awt.Dimension(50, 50));
        hetes8.setMinimumSize(new java.awt.Dimension(50, 50));
        hetes8.setPreferredSize(new java.awt.Dimension(50, 50));
        hetes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hetes8ActionPerformed(evt);
            }
        });
        szamok8.add(hetes8);

        nyolcas8.setBackground(new java.awt.Color(0, 255, 51));
        nyolcas8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        nyolcas8.setText("8");
        nyolcas8.setMaximumSize(new java.awt.Dimension(50, 50));
        nyolcas8.setMinimumSize(new java.awt.Dimension(50, 50));
        nyolcas8.setPreferredSize(new java.awt.Dimension(50, 50));
        nyolcas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyolcas8ActionPerformed(evt);
            }
        });
        szamok8.add(nyolcas8);

        kilences8.setBackground(new java.awt.Color(0, 255, 51));
        kilences8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        kilences8.setText("9");
        kilences8.setMaximumSize(new java.awt.Dimension(50, 50));
        kilences8.setMinimumSize(new java.awt.Dimension(50, 50));
        kilences8.setPreferredSize(new java.awt.Dimension(50, 50));
        kilences8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilences8ActionPerformed(evt);
            }
        });
        szamok8.add(kilences8);

        nullas8.setBackground(new java.awt.Color(0, 255, 51));
        nullas8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        nullas8.setText("0");
        nullas8.setMaximumSize(new java.awt.Dimension(50, 50));
        nullas8.setMinimumSize(new java.awt.Dimension(50, 50));
        nullas8.setPreferredSize(new java.awt.Dimension(50, 50));
        nullas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nullas8ActionPerformed(evt);
            }
        });
        szamok8.add(nullas8);

        xgomb8.setBackground(new java.awt.Color(0, 255, 51));
        xgomb8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        xgomb8.setText("x");
        xgomb8.setMaximumSize(new java.awt.Dimension(50, 50));
        xgomb8.setMinimumSize(new java.awt.Dimension(50, 50));
        xgomb8.setPreferredSize(new java.awt.Dimension(50, 50));
        szamok8.add(xgomb8);

        ygomb8.setBackground(new java.awt.Color(0, 255, 51));
        ygomb8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        ygomb8.setText("y");
        ygomb8.setMaximumSize(new java.awt.Dimension(50, 50));
        ygomb8.setMinimumSize(new java.awt.Dimension(50, 50));
        ygomb8.setPreferredSize(new java.awt.Dimension(50, 50));
        szamok8.add(ygomb8);

        bosszeadas40.setBackground(new java.awt.Color(255, 255, 255));
        bosszeadas40.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosszeadas40.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/IXgglOn.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosszeadas40.setToolTipText("");
        bosszeadas40.setBorder(null);
        bosszeadas40.setMinimumSize(new java.awt.Dimension(0, 0));
        bosszeadas40.setName(""); // NOI18N
        bosszeadas40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosszeadas40ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bosszeadas40);

        bkivonas8.setBackground(new java.awt.Color(255, 255, 255));
        bkivonas8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bkivonas8.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/E1zvKG7.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bkivonas8.setBorder(null);
        bkivonas8.setMinimumSize(new java.awt.Dimension(0, 0));
        bkivonas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkivonas8ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bkivonas8);

        bosszeadas41.setBackground(new java.awt.Color(255, 255, 255));
        bosszeadas41.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosszeadas41.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BJ4yusU.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosszeadas41.setToolTipText("");
        bosszeadas41.setBorder(null);
        bosszeadas41.setMinimumSize(new java.awt.Dimension(0, 0));
        bosszeadas41.setName(""); // NOI18N
        bosszeadas41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosszeadas41ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bosszeadas41);

        bosszeadas42.setBackground(new java.awt.Color(255, 255, 255));
        bosszeadas42.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosszeadas42.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/wxRhK3i.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosszeadas42.setToolTipText("");
        bosszeadas42.setBorder(null);
        bosszeadas42.setMinimumSize(new java.awt.Dimension(0, 0));
        bosszeadas42.setName(""); // NOI18N
        bosszeadas42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosszeadas42ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bosszeadas42);

        bosszeadas43.setBackground(new java.awt.Color(255, 255, 255));
        bosszeadas43.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosszeadas43.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BPVKHpZ.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosszeadas43.setToolTipText("");
        bosszeadas43.setBorder(null);
        bosszeadas43.setMinimumSize(new java.awt.Dimension(0, 0));
        bosszeadas43.setName(""); // NOI18N
        bosszeadas43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosszeadas43ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bosszeadas43);

        bosszeadas44.setBackground(new java.awt.Color(255, 255, 255));
        bosszeadas44.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bosszeadas44.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/YPyBcOe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bosszeadas44.setToolTipText("");
        bosszeadas44.setBorder(null);
        bosszeadas44.setMinimumSize(new java.awt.Dimension(0, 0));
        bosszeadas44.setName(""); // NOI18N
        bosszeadas44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosszeadas44ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bosszeadas44);

        bnyitozarojel8.setBackground(new java.awt.Color(255, 255, 255));
        bnyitozarojel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bnyitozarojel8.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/4xnGmGs.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bnyitozarojel8.setToolTipText("");
        bnyitozarojel8.setBorder(null);
        bnyitozarojel8.setMinimumSize(new java.awt.Dimension(0, 0));
        bnyitozarojel8.setName(""); // NOI18N
        bnyitozarojel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnyitozarojel8ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bnyitozarojel8);

        bbezarozarojel8.setBackground(new java.awt.Color(255, 255, 255));
        bbezarozarojel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bbezarozarojel8.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/w5eLMzB.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bbezarozarojel8.setToolTipText("");
        bbezarozarojel8.setBorder(null);
        bbezarozarojel8.setMinimumSize(new java.awt.Dimension(0, 0));
        bbezarozarojel8.setName(""); // NOI18N
        bbezarozarojel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbezarozarojel8ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(bbezarozarojel8);

        btorles8.setBackground(new java.awt.Color(255, 255, 255));
        btorles8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btorles8.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/5BUQAEv.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btorles8.setToolTipText("");
        btorles8.setBorder(null);
        btorles8.setMinimumSize(new java.awt.Dimension(0, 0));
        btorles8.setName(""); // NOI18N
        btorles8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btorles8ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(btorles8);

        begyenlosegjel8.setBackground(new java.awt.Color(255, 255, 255));
        begyenlosegjel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        begyenlosegjel8.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/3fxHcBe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        begyenlosegjel8.setToolTipText("");
        begyenlosegjel8.setBorder(null);
        begyenlosegjel8.setMinimumSize(new java.awt.Dimension(0, 0));
        begyenlosegjel8.setName(""); // NOI18N
        begyenlosegjel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                begyenlosegjel8ActionPerformed(evt);
            }
        });
        muveletjelpanel8.add(begyenlosegjel8);

        javax.swing.GroupLayout userinterface8Layout = new javax.swing.GroupLayout(userinterface8);
        userinterface8.setLayout(userinterface8Layout);
        userinterface8Layout.setHorizontalGroup(
            userinterface8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinterface8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(szamok8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muveletjelpanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userinterface8Layout.setVerticalGroup(
            userinterface8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userinterface8Layout.createSequentialGroup()
                .addGroup(userinterface8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(szamok8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muveletjelpanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout fopanel8Layout = new javax.swing.GroupLayout(fopanel8);
        fopanel8.setLayout(fopanel8Layout);
        fopanel8Layout.setHorizontalGroup(
            fopanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fopanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fopanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userinterface8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fopanel8Layout.createSequentialGroup()
                        .addGroup(fopanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bemenetlabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kimenetlabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fopanel8Layout.createSequentialGroup()
                        .addGroup(fopanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputslot8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputslot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        fopanel8Layout.setVerticalGroup(
            fopanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fopanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemenetlabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputslot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kimenetlabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputslot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userinterface8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        muveletijelek.setText("Műveleti Jelek");
        muveletijelek.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                muveletijelekStateChanged(evt);
            }
        });

        osszeadas.setSelected(true);
        osszeadas.setText("Összeadás");
        osszeadas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/IXgglOn.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        osszeadas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                osszeadasStateChanged(evt);
            }
        });
        osszeadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osszeadasMouseClicked(evt);
            }
        });
        osszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osszeadasActionPerformed(evt);
            }
        });
        muveletijelek.add(osszeadas);

        kivonas.setSelected(true);
        kivonas.setText("Kivonás");
        kivonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/E1zvKG7.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        kivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kivonasActionPerformed(evt);
            }
        });
        muveletijelek.add(kivonas);

        szorzas.setSelected(true);
        szorzas.setText("Szorzás");
        szorzas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BJ4yusU.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(szorzas);

        osztas.setSelected(true);
        osztas.setText("Osztás");
        osztas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/wxRhK3i.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        muveletijelek.add(osztas);

        hatvanyozas.setSelected(true);
        hatvanyozas.setText("Hatványozás (pow(a,b))");
        hatvanyozas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/BPVKHpZ.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        hatvanyozas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatvanyozasActionPerformed(evt);
            }
        });
        muveletijelek.add(hatvanyozas);

        gyokvonas.setSelected(true);
        gyokvonas.setText("Gyökvonás (sqrt(a,b))");
        gyokvonas.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/YPyBcOe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        gyokvonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gyokvonasActionPerformed(evt);
            }
        });
        muveletijelek.add(gyokvonas);

        nyitozarojel.setSelected(true);
        nyitozarojel.setText("Nyitó Zárójel");
        nyitozarojel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/4xnGmGs.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        nyitozarojel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nyitozarojelStateChanged(evt);
            }
        });
        nyitozarojel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nyitozarojelMouseClicked(evt);
            }
        });
        nyitozarojel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyitozarojelActionPerformed(evt);
            }
        });
        muveletijelek.add(nyitozarojel);

        bezarozarojel.setSelected(true);
        bezarozarojel.setText("Záró Zárójel");
        bezarozarojel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/w5eLMzB.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bezarozarojel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bezarozarojelStateChanged(evt);
            }
        });
        bezarozarojel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bezarozarojelMouseClicked(evt);
            }
        });
        bezarozarojel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bezarozarojelActionPerformed(evt);
            }
        });
        muveletijelek.add(bezarozarojel);

        torles.setSelected(true);
        torles.setText("Törlés");
        torles.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/5BUQAEv.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        torles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torlesActionPerformed(evt);
            }
        });
        muveletijelek.add(torles);

        egyenlosegjel.setSelected(true);
        egyenlosegjel.setText("Egyenlőségjel");
        egyenlosegjel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/3fxHcBe.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        egyenlosegjel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egyenlosegjelActionPerformed(evt);
            }
        });
        muveletijelek.add(egyenlosegjel);

        jMenuBar1.add(muveletijelek);

        fejleszto.setText("Fejlesztő: Menyhárt Tamás (DE-IK)");
        jMenuBar1.add(fejleszto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fopanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fopanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void osszeadasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_osszeadasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasStateChanged

    private void osszeadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osszeadasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasMouseClicked

    private void osszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osszeadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osszeadasActionPerformed

    private void kivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kivonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kivonasActionPerformed

    private void hatvanyozasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatvanyozasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hatvanyozasActionPerformed

    private void gyokvonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gyokvonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gyokvonasActionPerformed

    private void nyitozarojelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nyitozarojelStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nyitozarojelStateChanged

    private void nyitozarojelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nyitozarojelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nyitozarojelMouseClicked

    private void nyitozarojelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyitozarojelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyitozarojelActionPerformed

    private void bezarozarojelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bezarozarojelStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bezarozarojelStateChanged

    private void bezarozarojelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bezarozarojelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bezarozarojelMouseClicked

    private void bezarozarojelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bezarozarojelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bezarozarojelActionPerformed

    private void torlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_torlesActionPerformed

    private void egyenlosegjelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egyenlosegjelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egyenlosegjelActionPerformed

    private void muveletijelekStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_muveletijelekStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_muveletijelekStateChanged

    private void outputslot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputslot8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputslot8ActionPerformed

    private void inputslot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputslot8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputslot8ActionPerformed

    private void egyes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egyes8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"1");
    }//GEN-LAST:event_egyes8ActionPerformed

    private void kettes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kettes8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"2");
    }//GEN-LAST:event_kettes8ActionPerformed

    private void harmas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harmas8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"3");
    }//GEN-LAST:event_harmas8ActionPerformed

    private void negyes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negyes8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"4");
    }//GEN-LAST:event_negyes8ActionPerformed

    private void otos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otos8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"5");
    }//GEN-LAST:event_otos8ActionPerformed

    private void hatos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatos8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"6");
    }//GEN-LAST:event_hatos8ActionPerformed

    private void hetes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hetes8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"7");
    }//GEN-LAST:event_hetes8ActionPerformed

    private void nyolcas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyolcas8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"8");
    }//GEN-LAST:event_nyolcas8ActionPerformed

    private void kilences8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilences8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"9");
    }//GEN-LAST:event_kilences8ActionPerformed

    private void nullas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nullas8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"0");
    }//GEN-LAST:event_nullas8ActionPerformed

    private void bosszeadas40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosszeadas40ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"+");
    }//GEN-LAST:event_bosszeadas40ActionPerformed

    private void bkivonas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkivonas8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"-");
    }//GEN-LAST:event_bkivonas8ActionPerformed

    private void bosszeadas41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosszeadas41ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"*");
    }//GEN-LAST:event_bosszeadas41ActionPerformed

    private void bosszeadas42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosszeadas42ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"/");
    }//GEN-LAST:event_bosszeadas42ActionPerformed

    private void bosszeadas43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosszeadas43ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"pow(");
    }//GEN-LAST:event_bosszeadas43ActionPerformed

    private void bosszeadas44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosszeadas44ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"sqrt(");
    }//GEN-LAST:event_bosszeadas44ActionPerformed

    private void bnyitozarojel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnyitozarojel8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+"(");
    }//GEN-LAST:event_bnyitozarojel8ActionPerformed

    private void bbezarozarojel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbezarozarojel8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText()+")");
    }//GEN-LAST:event_bbezarozarojel8ActionPerformed

    private void btorles8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btorles8ActionPerformed
        // TODO add your handling code here:
        inputslot.setText(inputslot.getText().substring(0,inputslot.getText().length()-1));
    }//GEN-LAST:event_btorles8ActionPerformed

    private void begyenlosegjel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_begyenlosegjel8ActionPerformed
        // TODO add your handling code here:
        //muveletek();
        //kifertelmezes();
    }//GEN-LAST:event_begyenlosegjel8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbezarozarojel;
    private javax.swing.JButton bbezarozarojel1;
    private javax.swing.JButton bbezarozarojel2;
    private javax.swing.JButton bbezarozarojel3;
    private javax.swing.JButton bbezarozarojel4;
    private javax.swing.JButton bbezarozarojel5;
    private javax.swing.JButton bbezarozarojel6;
    private javax.swing.JButton bbezarozarojel7;
    private javax.swing.JButton bbezarozarojel8;
    private javax.swing.JButton begyenlosegjel;
    private javax.swing.JButton begyenlosegjel1;
    private javax.swing.JButton begyenlosegjel2;
    private javax.swing.JButton begyenlosegjel3;
    private javax.swing.JButton begyenlosegjel4;
    private javax.swing.JButton begyenlosegjel5;
    private javax.swing.JButton begyenlosegjel6;
    private javax.swing.JButton begyenlosegjel7;
    private javax.swing.JButton begyenlosegjel8;
    private javax.swing.JLabel bemenetlabel;
    private javax.swing.JLabel bemenetlabel1;
    private javax.swing.JLabel bemenetlabel2;
    private javax.swing.JLabel bemenetlabel3;
    private javax.swing.JLabel bemenetlabel4;
    private javax.swing.JLabel bemenetlabel5;
    private javax.swing.JLabel bemenetlabel6;
    private javax.swing.JLabel bemenetlabel7;
    private javax.swing.JLabel bemenetlabel8;
    private javax.swing.JCheckBoxMenuItem bezarozarojel;
    private javax.swing.JButton bkivonas;
    private javax.swing.JButton bkivonas1;
    private javax.swing.JButton bkivonas2;
    private javax.swing.JButton bkivonas3;
    private javax.swing.JButton bkivonas4;
    private javax.swing.JButton bkivonas5;
    private javax.swing.JButton bkivonas6;
    private javax.swing.JButton bkivonas7;
    private javax.swing.JButton bkivonas8;
    private javax.swing.JButton bnyitozarojel;
    private javax.swing.JButton bnyitozarojel1;
    private javax.swing.JButton bnyitozarojel2;
    private javax.swing.JButton bnyitozarojel3;
    private javax.swing.JButton bnyitozarojel4;
    private javax.swing.JButton bnyitozarojel5;
    private javax.swing.JButton bnyitozarojel6;
    private javax.swing.JButton bnyitozarojel7;
    private javax.swing.JButton bnyitozarojel8;
    private javax.swing.JButton bosszeadas;
    private javax.swing.JButton bosszeadas1;
    private javax.swing.JButton bosszeadas10;
    private javax.swing.JButton bosszeadas11;
    private javax.swing.JButton bosszeadas12;
    private javax.swing.JButton bosszeadas13;
    private javax.swing.JButton bosszeadas14;
    private javax.swing.JButton bosszeadas15;
    private javax.swing.JButton bosszeadas16;
    private javax.swing.JButton bosszeadas17;
    private javax.swing.JButton bosszeadas18;
    private javax.swing.JButton bosszeadas19;
    private javax.swing.JButton bosszeadas2;
    private javax.swing.JButton bosszeadas20;
    private javax.swing.JButton bosszeadas21;
    private javax.swing.JButton bosszeadas22;
    private javax.swing.JButton bosszeadas23;
    private javax.swing.JButton bosszeadas24;
    private javax.swing.JButton bosszeadas25;
    private javax.swing.JButton bosszeadas26;
    private javax.swing.JButton bosszeadas27;
    private javax.swing.JButton bosszeadas28;
    private javax.swing.JButton bosszeadas29;
    private javax.swing.JButton bosszeadas3;
    private javax.swing.JButton bosszeadas30;
    private javax.swing.JButton bosszeadas31;
    private javax.swing.JButton bosszeadas32;
    private javax.swing.JButton bosszeadas33;
    private javax.swing.JButton bosszeadas34;
    private javax.swing.JButton bosszeadas35;
    private javax.swing.JButton bosszeadas36;
    private javax.swing.JButton bosszeadas37;
    private javax.swing.JButton bosszeadas38;
    private javax.swing.JButton bosszeadas39;
    private javax.swing.JButton bosszeadas4;
    private javax.swing.JButton bosszeadas40;
    private javax.swing.JButton bosszeadas41;
    private javax.swing.JButton bosszeadas42;
    private javax.swing.JButton bosszeadas43;
    private javax.swing.JButton bosszeadas44;
    private javax.swing.JButton bosszeadas5;
    private javax.swing.JButton bosszeadas6;
    private javax.swing.JButton bosszeadas7;
    private javax.swing.JButton bosszeadas8;
    private javax.swing.JButton bosszeadas9;
    private javax.swing.JButton btorles;
    private javax.swing.JButton btorles1;
    private javax.swing.JButton btorles2;
    private javax.swing.JButton btorles3;
    private javax.swing.JButton btorles4;
    private javax.swing.JButton btorles5;
    private javax.swing.JButton btorles6;
    private javax.swing.JButton btorles7;
    private javax.swing.JButton btorles8;
    private javax.swing.JCheckBoxMenuItem egyenlosegjel;
    private javax.swing.JButton egyes;
    private javax.swing.JButton egyes1;
    private javax.swing.JButton egyes2;
    private javax.swing.JButton egyes3;
    private javax.swing.JButton egyes4;
    private javax.swing.JButton egyes5;
    private javax.swing.JButton egyes6;
    private javax.swing.JButton egyes7;
    private javax.swing.JButton egyes8;
    private javax.swing.JMenu fejleszto;
    private javax.swing.JPanel fopanel;
    private javax.swing.JPanel fopanel1;
    private javax.swing.JPanel fopanel2;
    private javax.swing.JPanel fopanel3;
    private javax.swing.JPanel fopanel4;
    private javax.swing.JPanel fopanel5;
    private javax.swing.JPanel fopanel6;
    private javax.swing.JPanel fopanel7;
    private javax.swing.JPanel fopanel8;
    private javax.swing.JCheckBoxMenuItem gyokvonas;
    private javax.swing.JButton harmas;
    private javax.swing.JButton harmas1;
    private javax.swing.JButton harmas2;
    private javax.swing.JButton harmas3;
    private javax.swing.JButton harmas4;
    private javax.swing.JButton harmas5;
    private javax.swing.JButton harmas6;
    private javax.swing.JButton harmas7;
    private javax.swing.JButton harmas8;
    private javax.swing.JButton hatos;
    private javax.swing.JButton hatos1;
    private javax.swing.JButton hatos2;
    private javax.swing.JButton hatos3;
    private javax.swing.JButton hatos4;
    private javax.swing.JButton hatos5;
    private javax.swing.JButton hatos6;
    private javax.swing.JButton hatos7;
    private javax.swing.JButton hatos8;
    private javax.swing.JCheckBoxMenuItem hatvanyozas;
    private javax.swing.JButton hetes;
    private javax.swing.JButton hetes1;
    private javax.swing.JButton hetes2;
    private javax.swing.JButton hetes3;
    private javax.swing.JButton hetes4;
    private javax.swing.JButton hetes5;
    private javax.swing.JButton hetes6;
    private javax.swing.JButton hetes7;
    private javax.swing.JButton hetes8;
    private java.awt.TextField inputslot;
    private java.awt.TextField inputslot1;
    private java.awt.TextField inputslot2;
    private java.awt.TextField inputslot3;
    private java.awt.TextField inputslot4;
    private java.awt.TextField inputslot5;
    private java.awt.TextField inputslot6;
    private java.awt.TextField inputslot7;
    private java.awt.TextField inputslot8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton kettes;
    private javax.swing.JButton kettes1;
    private javax.swing.JButton kettes2;
    private javax.swing.JButton kettes3;
    private javax.swing.JButton kettes4;
    private javax.swing.JButton kettes5;
    private javax.swing.JButton kettes6;
    private javax.swing.JButton kettes7;
    private javax.swing.JButton kettes8;
    private javax.swing.JButton kilences;
    private javax.swing.JButton kilences1;
    private javax.swing.JButton kilences2;
    private javax.swing.JButton kilences3;
    private javax.swing.JButton kilences4;
    private javax.swing.JButton kilences5;
    private javax.swing.JButton kilences6;
    private javax.swing.JButton kilences7;
    private javax.swing.JButton kilences8;
    private javax.swing.JLabel kimenetlabel;
    private javax.swing.JLabel kimenetlabel1;
    private javax.swing.JLabel kimenetlabel2;
    private javax.swing.JLabel kimenetlabel3;
    private javax.swing.JLabel kimenetlabel4;
    private javax.swing.JLabel kimenetlabel5;
    private javax.swing.JLabel kimenetlabel6;
    private javax.swing.JLabel kimenetlabel7;
    private javax.swing.JLabel kimenetlabel8;
    private javax.swing.JCheckBoxMenuItem kivonas;
    private javax.swing.JMenu muveletijelek;
    private javax.swing.JPanel muveletjelpanel;
    private javax.swing.JPanel muveletjelpanel1;
    private javax.swing.JPanel muveletjelpanel2;
    private javax.swing.JPanel muveletjelpanel3;
    private javax.swing.JPanel muveletjelpanel4;
    private javax.swing.JPanel muveletjelpanel5;
    private javax.swing.JPanel muveletjelpanel6;
    private javax.swing.JPanel muveletjelpanel7;
    private javax.swing.JPanel muveletjelpanel8;
    private javax.swing.JButton negyes;
    private javax.swing.JButton negyes1;
    private javax.swing.JButton negyes2;
    private javax.swing.JButton negyes3;
    private javax.swing.JButton negyes4;
    private javax.swing.JButton negyes5;
    private javax.swing.JButton negyes6;
    private javax.swing.JButton negyes7;
    private javax.swing.JButton negyes8;
    private javax.swing.JButton nullas;
    private javax.swing.JButton nullas1;
    private javax.swing.JButton nullas2;
    private javax.swing.JButton nullas3;
    private javax.swing.JButton nullas4;
    private javax.swing.JButton nullas5;
    private javax.swing.JButton nullas6;
    private javax.swing.JButton nullas7;
    private javax.swing.JButton nullas8;
    private javax.swing.JCheckBoxMenuItem nyitozarojel;
    private javax.swing.JButton nyolcas;
    private javax.swing.JButton nyolcas1;
    private javax.swing.JButton nyolcas2;
    private javax.swing.JButton nyolcas3;
    private javax.swing.JButton nyolcas4;
    private javax.swing.JButton nyolcas5;
    private javax.swing.JButton nyolcas6;
    private javax.swing.JButton nyolcas7;
    private javax.swing.JButton nyolcas8;
    private javax.swing.JCheckBoxMenuItem osszeadas;
    private javax.swing.JCheckBoxMenuItem osztas;
    private javax.swing.JButton otos;
    private javax.swing.JButton otos1;
    private javax.swing.JButton otos2;
    private javax.swing.JButton otos3;
    private javax.swing.JButton otos4;
    private javax.swing.JButton otos5;
    private javax.swing.JButton otos6;
    private javax.swing.JButton otos7;
    private javax.swing.JButton otos8;
    private java.awt.TextField outputslot;
    private java.awt.TextField outputslot1;
    private java.awt.TextField outputslot2;
    private java.awt.TextField outputslot3;
    private java.awt.TextField outputslot4;
    private java.awt.TextField outputslot5;
    private java.awt.TextField outputslot6;
    private java.awt.TextField outputslot7;
    private java.awt.TextField outputslot8;
    private javax.swing.JPanel szamok;
    private javax.swing.JPanel szamok1;
    private javax.swing.JPanel szamok2;
    private javax.swing.JPanel szamok3;
    private javax.swing.JPanel szamok4;
    private javax.swing.JPanel szamok5;
    private javax.swing.JPanel szamok6;
    private javax.swing.JPanel szamok7;
    private javax.swing.JPanel szamok8;
    private javax.swing.JCheckBoxMenuItem szorzas;
    private javax.swing.JCheckBoxMenuItem torles;
    private javax.swing.JPanel userinterface;
    private javax.swing.JPanel userinterface1;
    private javax.swing.JPanel userinterface2;
    private javax.swing.JPanel userinterface3;
    private javax.swing.JPanel userinterface4;
    private javax.swing.JPanel userinterface5;
    private javax.swing.JPanel userinterface6;
    private javax.swing.JPanel userinterface7;
    private javax.swing.JPanel userinterface8;
    private javax.swing.JButton xgomb;
    private javax.swing.JButton xgomb1;
    private javax.swing.JButton xgomb2;
    private javax.swing.JButton xgomb3;
    private javax.swing.JButton xgomb4;
    private javax.swing.JButton xgomb5;
    private javax.swing.JButton xgomb6;
    private javax.swing.JButton xgomb7;
    private javax.swing.JButton xgomb8;
    private javax.swing.JButton ygomb;
    private javax.swing.JButton ygomb1;
    private javax.swing.JButton ygomb2;
    private javax.swing.JButton ygomb3;
    private javax.swing.JButton ygomb4;
    private javax.swing.JButton ygomb5;
    private javax.swing.JButton ygomb6;
    private javax.swing.JButton ygomb7;
    private javax.swing.JButton ygomb8;
    // End of variables declaration//GEN-END:variables
}
